# Generated by Django 5.0.4 on 2024-06-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_package_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_date',
        ),
    ]
