# Generated by Django 5.0.4 on 2024-04-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_container', models.IntegerField()),
                ('size', models.CharField()),
                ('location', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'Boxpackage',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('status', models.CharField()),
            ],
            options={
                'db_table': 'Package',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('phone', models.CharField(unique=True)),
                ('email', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('capacity', models.CharField()),
                ('fk_boxpackage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.boxpackage')),
            ],
            options={
                'db_table': 'Container',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_departure', models.DateTimeField(auto_now_add=True)),
                ('data_receiving', models.DateTimeField()),
                ('fk_from_boxpackage_location', models.ForeignKey(blank=True, db_column='fk_from_boxpackage_location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.boxpackage', to_field='location')),
                ('fk_from_container_num', models.ForeignKey(blank=True, db_column='fk_from_container_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.container', to_field='number')),
                ('fk_to_boxpackage_location', models.ForeignKey(blank=True, db_column='fk_to_boxpackage_location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_fk_to_boxpackage_location_set', to='crm.boxpackage', to_field='location')),
                ('fk_to_container_num', models.ForeignKey(blank=True, db_column='fk_to_container_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_fk_to_container_num_set', to='crm.container', to_field='number')),
                ('fk_package_number', models.OneToOneField(blank=True, db_column='fk_package_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.package')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.user')),
            ],
            options={
                'db_table': 'Delivery',
            },
        ),
    ]
