# Generated by Django 5.0.4 on 2024-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='size_package',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
    ]
