# Generated by Django 5.0.4 on 2024-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_user_password_alter_user_first_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxpackage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='data_departure',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True),
        ),
    ]
