# Generated by Django 5.0.4 on 2024-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_delivery_size_package_users_is_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='fk_to_boxpackage',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='fk_from_boxpackage',
        ),
        migrations.RemoveField(
            model_name='container',
            name='fk_boxpackage_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='fk_package',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='to_user_email',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='to_user_phone',
        ),
        migrations.DeleteModel(
            name='Boxpackage',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
