# Generated by Django 5.0.4 on 2024-04-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_boxpackage_id_alter_container_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='fk_user',
            new_name='fk_users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
